### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ShootingKing-AM** [PlatinBae/PlatinBae#5]
I have question... Why @PlatinBae so cute ?

**Comment by PlatinBae** [comment]
![gif](https://c.tenor.com/25Hi28SAcCgAAAAM/i-dont-know-compilation-dont-know.gif)

**Comment by bitglitcher** [comment]
what the hell...

**Comment by NMW03** [comment]
wtf

**Comment by beyazit** [comment]
bruh

**Comment by ShootingKing-AM** [comment]
Sorry guys, but it was bothering me that I had to ask, @PlatinBae is so cute, that I feel it's really unfair on us mere mortals :c

**Comment by bitglitcher** [comment]
I feel like there is more to it. I need more explanation.

**Comment by bitglitcher** [comment]
I never thought you could use github as a dating app.

**Comment by ShootingKing-AM** [comment]
> I feel like there is more to it. I need more explanation.

![](https://c.tenor.com/q0nNfTktQ7wAAAAM/crying-anime.gif)
